name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'

    - name: Install backend dependencies
      run: |
        cd backend
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run backend tests
      run: |
        cd backend
        pytest -v -s || (cat /home/runner/work/AIPI561Book/AIPI561Book/backend/*.log && exit 1)

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '12.22.9'  # Updated Node.js version

    - name: Install frontend dependencies
      run: |
        cd frontend
        npm install

    - name: Run frontend tests
      run: |
        cd frontend
        npm test -- --passWithNoTests || (cat /home/runner/.npm/_logs/*.log && exit 1)

    - name: Build frontend
      env:
        CI: false
      run: |
        cd frontend
        npm run build --verbose
